name: happy_puppies_app
description: "Happy Puppies App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path: ^1.8.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Ruta a la imagen del fondo
  assets:
    - assets/images/bienvenida_background.png
    - assets/images/happypuppies_negro.png
    - assets/images/login_background.png

  # Configuración de la fuente Poppins
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
